//LOGIN USER ACTION TYPE
export const REQUEST_USER_LOGIN = "REQUEST_USER_LOGIN";
export const SUCCESS_USER_LOGIN = "SUCCESS_USER_LOGIN";
export const FAILURE_USER_LOGIN = "FAILURE_USER_LOGIN";

// USER INFO
export const GET_USER_INFO = "GET_USER_INFO";

// LOGOUT 
export const LOGOUT = "LOGOUT"

// GET ALL LOTTERY
export const REQUEST_LOTTERY_TICKET = "REQUEST_LOTTERY_TICKET"
export const SUCCESS_LOTTERY_TICKET = "SUCCESS_LOTTERY_TICKET"
export const FAILURE_LOTTERY_TICKET = "FAILURE_LOTTERY_TICKET"

// GET LOTTERY BY ID
export const REQUEST_LOTTERY_ID_TICKET = "REQUEST_LOTTERY_ID_TICKET"
export const SUCCESS_LOTTERY_BY_ID = "SUCCESS_LOTTERY_BY_ID"

// GET LOTTERIES OF LOOGED IN USER
export const REQUEST_CUSTOMER_LOTTERIES = "REQUEST_CUSTOMER_LOTTERIES"
export const SUCCESS_CUSTOMER_LOTTERIES = "SUCCESS_CUSTOMER_LOTTERIES"

// GET LOTTERY RESULTS 
export const REQUEST_LOTTERY_RESULTS = "REQUEST_LOTTERY_RESULTS"
export const GET_LOTTERY_RESULTS = "GET_LOTTERY_RESULTS"

// GET DYNAMIC CONTENT
export const DYNAMIC_CONTENT = "DYNAMIC_CONTENT"

// SETTINGS
export const SETTINGS_REQUEST= "SETTINGS_REQUEST"
export const SETTINGS_SUCCESS= "SETTINGS_SUCCESS"
export const SETTINGS_FAILURE= "SETTINGS_FAILURE"

export const COUPON_REQUEST= "COUPON_REQUEST"
export const COUPON_SUCCESS= "COUPON_SUCCESS"
export const COUPON_FAILURE= "COUPON_FAILURE"